#!/bin/sh

export PATH=$PATH:"bin/"

rm -f disco.imagen
echo "FS BORRAT\n"

if [ ! -d bin ]; then
	mkdir bin/
fi

make clean
echo
make
echo
./bin/mi_mkfs disco.imagen 200000 # 200 MB
cd tests
./make_tests
cd ..
echo "OK GENERAL"
